# Generated by Django 2.1 on 2018-08-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('JSON', 'Json'), ('PLAINTEXT', 'Plaintext'), ('BINARY', 'Binary')], max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='properties',
            field=models.ManyToManyField(blank=True, to='devices.Property'),
        ),
    ]
